image:
  file: Dockerfile

ports:
  - port: 3000
    onOpen: open-preview
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: ignore

tasks:
  - init: >
      yarn &&
      yarn --cwd ./browser-app start

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addComment: false
    addBadge: false
